
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Users/mather01/.vcpkg/artifacts/2139c4c6/tools.kitware.cmake/3.31.5/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:4 (project)"
    message: |
      The system is: Darwin - 24.5.0 - arm64
...
